name: ret-env
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.9
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=10.0.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libevent=2.1.12
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libllvm10=10.0.1
  - libpng=1.6.37
  - libpq=12.9
  - libstdcxx-ng=11.2.0
  - libtiff=4.4.0
  - libuuid=1.41.5
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.9.14
  - libxslt=1.1.35
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - nspr=4.33
  - nss=3.74
  - numpy-base=1.21.5
  - openssl=1.1.1s
  - packaging=21.3
  - pcre=8.45
  - pip=22.1.2
  - ply=3.11
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - python=3.7.10
  - python-dateutil=2.8.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtwebkit=5.212
  - readline=8.1.2
  - setuptools=63.4.1
  - sip=6.6.2
  - six=1.16.0
  - sqlite=3.39.2
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - anyio==3.6.2
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - attrs==22.1.0
    - babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - blis==0.7.9
    - catalogue==2.0.8
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.1.3
    - confection==0.0.3
    - cupy-cuda11x==11.3.0
    - cupy-wheel==11.3.0
    - cymem==2.0.7
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - en-core-web-sm==3.4.1
    - entrypoints==0.4
    - faiss-cpu==1.7.2
    - faiss-gpu==1.7.2
    - fastjsonschema==2.16.2
    - fastrlock==0.8.1
    - filelock==3.8.0
    - huggingface-hub==0.9.1
    - idna==3.3
    - importlib-metadata==4.12.0
    - importlib-resources==5.10.0
    - ipykernel==6.16.2
    - ipython==7.34.0
    - ipython-genutils==0.2.0
    - ir-measures==0.1.4
    - jedi==0.18.2
    - jinja2==3.1.2
    - joblib==1.1.0
    - json5==0.9.10
    - jsonschema==4.17.0
    - jupyter-client==7.4.7
    - jupyter-core==4.11.2
    - jupyter-server==1.23.3
    - jupyterlab==3.5.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.16.3
    - langcodes==3.3.0
    - littleutils==0.2.2
    - markupsafe==2.1.1
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - murmurhash==1.0.9
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - nltk==3.7
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numpy==1.21.6
    - outdated==0.2.2
    - pandas==1.3.5
    - pandas-flavor==0.2.0
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pathy==0.10.0
    - patsy==0.5.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pingouin==0.5.2
    - pkgutil-resolve-name==1.3.10
    - preshed==3.0.8
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.33
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pycparser==2.21
    - pydantic==1.10.2
    - pygments==2.13.0
    - pyrsistent==0.19.2
    - pytrec-eval-terrier==0.5.1
    - pytz==2022.2.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - regex==2022.8.17
    - requests==2.28.1
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - seaborn==0.12.1
    - send2trash==1.8.0
    - sentence-transformers==2.2.2
    - sentencepiece==0.1.97
    - smart-open==5.2.1
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - spacy==3.4.3
    - spacy-legacy==3.0.10
    - spacy-loggers==1.0.3
    - srsly==2.4.5
    - statsmodels==0.13.5
    - tabulate==0.9.0
    - terminado==0.17.0
    - thinc==8.1.5
    - threadpoolctl==3.1.0
    - tinycss2==1.2.1
    - tokenizers==0.12.1
    - tomli==2.0.1
    - torch==1.10.1+cu113
    - torchvision==0.11.2+cu113
    - tqdm==4.64.1
    - traitlets==5.5.0
    - transformers==4.21.2
    - typer==0.7.0
    - typing-extensions==4.1.1
    - urllib3==1.26.12
    - wasabi==0.10.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - xarray==0.20.2
    - zipp==3.8.1
